# Generated by Django 5.2.7 on 2025-10-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='migrations/')),
                ('target_model', models.CharField(choices=[('gso_inventory.InventoryItem', 'Inventory Items'), ('gso_reports.WorkAccomplishmentReport', 'Work Accomplishment Reports'), ('gso_requests.ServiceRequest', 'Service Requests')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
